# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

queue:
  name: 'Hosted VS2017'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
# The next two steps are to handle missing rootDir and outDir in the tsconfig.json
# These can be removed once we fix support in the build task.
- script: |
    npm i -g strip-json-comments-cli

- script: |
    strip-json-comments tsconfig.json | jq ".compilerOptions[\"rootDir\"] = \"src\"" | jq ".compilerOptions[\"outDir\"] = \"src\"" > tsconfig.json

- script: |
    cat tsconfig.json

- script: |
    yarn install
    yarn run build
  displayName: 'npm install and build'

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav-prod'
    githubServiceConnection: 'arjun27 (3)'
    languages: typescript
